### PR TITLE
Documentation enhacement

### PR DESCRIPTION
**Pull request by greenled**
Fixed some typos and added example code for use with `mongodb-driver-async` and with `SBT`.

### CODE REVIEW

**Comment by ylemoigne** [comment]
Great. Thanks you. 

There is still a typo in the readme (first synchronous is missing the H). Can you fix it and add yourself to the changelog part of the README ;)

I'll do a release tomorrow.

**Comment by greenled** [comment]
For the async example I would prefer to use lambdas

```
    blogPosts.insertMany(asList(blogPost1, blogPost2), (aVoid, throwable) -> {
        // Do something with here
    });

    blogPosts.find().into(new ArrayList<>(), (blogPostsList, throwable) -> {
        // Do something with here with blogPostsList
    });
```

**Comment by greenled** [comment]
Great, will wait for the release. And thank you for the codec.

**Comment by ylemoigne** [comment]
New version is pushed on bintray :).

**Comment by greenled** [comment]
Cool

**Pull request merged**
